### ISSUE TITLE
add docker-compose with prometheus

### ISSUE THREAD

**Issue by ghost** [ckluenter/aleph-exporter#6]
Hi @ckluenter,

Hope you are all well !

I work also with aleph and I am gopher, so I found your interesting repository.

I was wondering if you could add prometheus components in a docker-compose to have a stack to bootstrap aleph-exporter ?

Thanks for any inputs or insights on that.

Cheers,
X

**Comment by ckluenter** [comment]
Hi,

I use it the other way around. I added the aleph-exporter to the docker-compose of aleph. This way I have one exporter in every aleph instance. This is how it looks:
``` 
aleph_exporter:
    image: ckluenter/alephexporter:latest
    container_name: alephexporter
    ports:
      - "8080:8080"
    env_file:
      - aleph-exporter.env
```

**Comment by ghost** [comment]
Thanks for your reply :-) 

Other question, how did you setup grafana and prometheus config files ? can you share these config files ?

**Comment by ckluenter** [comment]
In prometheus.yml I added this to the scrape_config:
```
  - job_name: 'aleph'
    static_configs:
      - targets:
        - my_aleph_hostname:8080
```

I should probably add an example grafana dashboard to this repo and update the documentation. Will do this in the next days. Thanks for the input :)
